#!/usr/bin/perl

my @fred = qw/ 1 3 5 7 9 /;
my $fred_total = &total(@fred);
print "The total of \@fred is $fred_total.\n";
print "Enter some numbers: ";
my $user_total = &total(<STDIN>);

print "Your total is $user_total\n";


sub total {
	my @nums = @_;
	my $sum = 0;
	foreach (@nums) {
		$sum += $_;
	}
	$sum;
}

