#!/usr/bin/perl

$secret = int(1 + rand 100);

print("Guess a number between 1 and 100: ");
while(<>) {
	chomp;
	last if /(quit)|(exit)|^\s*$/i;
	if ($_ == $secret) {
		print "You guessed right!\n";
		last;
	}
	$_ > $secret ? print "Too high\n" : print "Too low\n";
	print("Guess a number between 1 and 100: ");
}
